version: '3.9'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    restart: always
    env_file:
      - .env
    depends_on:
      - flask_db
    networks:
      - my_network
    expose:
      - 5000

  flask_db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    volumes:
      - 'flask_db_data:/var/lib/postgresql/data'
    networks:
      - my_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    depends_on:
      - flask_app
    networks:
      - my_network

volumes:
  flask_db_data:

networks:
  my_network: